name = "AP"
author = "TylerS1066"
version = "1.20.4_alpha-1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f44f805435452cb6fae08e309804f189c91aa66c8adbfd474473d56d0f331c4"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
