name = "AP"
author = "TylerS1066"
version = "1.20.1_r6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ce831bfce2a66bafa59a10183686e1415125496074aecb4297992446efcbaf1"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
