name = "AP"
author = "TylerS1066"
version = "1.20.1_r1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95c4db90fd8c1598edc97521266538fa31820d74d2cf58ecc59a1e399b9df5bb"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
