name = "AP"
author = "TylerS1066"
version = "1.20.4_r0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d91e7d56003e7e5e33c58839457b6947d217aa620af2a45744187251c211ef5a"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
