name = "AP"
author = "TylerS1066"
version = "1.20.4_r0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71c9bf7ab9ecaba9a0c80779564627628994e439e720a684355256f72210fc68"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
