name = "AP"
author = "TylerS1066"
version = "1.20.2_r0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fff4ed8ffb57da7516a23aaca88cd6b7ef5ac21a99d77e5bee71a4540ab62e8a"

[versions]
fabric = "0.14.23"
minecraft = "1.20.2"

[options]
acceptable-game-versions = ["1.20.2"]
