name = "AP"
author = "TylerS1066"
version = "1.20.2_r0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b813c3175569134d143781c20136433ebbc4668955cb1969000a7870757dac7"

[versions]
fabric = "0.14.23"
minecraft = "1.20.2"

[options]
acceptable-game-versions = ["1.20.4"]
